name: Github Pages
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.13'
          cache: 'npm'
      - name: Build with NPM
        run: |
          npm install
          npm run build
      - name: Archive artifact
        run: |
          tar \
            --dereference --hard-dereference \
            --directory build \
            -cvf ${{ runner.temp }}/artifact.tar \
            --exclude=.git \
            --exclude=.github \
            .
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
